name: Android CI

on:
 pull_request:
    branches:
      - 'main'
 push:
    branches:
      - 'main'

jobs:
  test:
    name: Run UI Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: Download Dependencies
      - run: ./gradlew androidDependencies
         
      - name: UI tests
        run: ./gradlew lint test

